import { escapeHtml } from "../components/agreements/premiumAgreementDocumentHtml";
import type { LegalRedlineBlock, LegalRedlineDocumentViewModel, LegalRedlineSegment } from "./legalRedlineBlocks";
import { mergeAdjacentRedlineSegmentsAllTypes } from "./legalRedlineBlocks";
import type { HumanReviewStructuredForPdf } from "./recipientHumanReviewSummaryModel";

export type RecipientPreviewPdfExportKind = "original" | "proposed" | "redline";

/** Audit strip for redline PDF exports (first-page header box). */
export type RecipientRedlinePdfAuditMeta = {
  agreementId: string;
  agreementTitle?: string | null;
  reviewerDisplayName?: string | null;
  reviewerEmail?: string | null;
  generatedAt: Date;
};

const P_STYLE =
  "margin:0 0 14px;line-height:1.72;font-size:15px;color:#0f172a;font-family:Georgia,'Times New Roman',Times,serif;text-align:left;";
/** Retained — readable body text */
const SPAN_SAME = `color:#0f172a;font:inherit;`;
/** Insertions — soft green emphasis (no slab blocks) */
const SPAN_INS = `color:#14532d;font:inherit;background:rgba(220,252,231,0.85);text-decoration:underline;text-decoration-color:#15803d;text-underline-offset:3px;padding:0 1px;border-radius:2px;`;
/** Deletions — soft rose strikethrough */
const SPAN_DEL = `color:#7f1d1d;font:inherit;text-decoration:line-through;text-decoration-color:rgba(190,18,60,0.45);background:rgba(255,241,242,0.65);padding:0 1px;border-radius:2px;`;

function spanForInlineSegment(type: LegalRedlineSegment["type"], line: string): string {
  const inner = escapeHtml(line.length ? line : "\u00a0");
  if (type === "same") return `<span style="${SPAN_SAME}">${inner}</span>`;
  if (type === "insert") return `<span style="${SPAN_INS}">${inner}</span>`;
  return `<span style="${SPAN_DEL}">${inner}</span>`;
}

function formatAuditGeneratedLine(d: Date): string {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone ?? "UTC";
    const main = new Intl.DateTimeFormat(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
      timeZone: tz,
    }).format(d);
    const tzParts = new Intl.DateTimeFormat(undefined, {
      timeZoneName: "short",
      timeZone: tz,
    }).formatToParts(d);
    const tzName = tzParts.find((p) => p.type === "timeZoneName")?.value ?? "";
    return tzName ? `${main} ${tzName}` : main;
  } catch {
    return d.toISOString();
  }
}

function buildAuditHeader(meta: RecipientRedlinePdfAuditMeta): string {
  const title = (meta.agreementTitle || "").trim();
  const reviewer = (meta.reviewerDisplayName || "").trim();
  const email = (meta.reviewerEmail || "").trim();
  const lines: string[] = [];
  lines.push(
    `<div style="font-weight:600;font-size:13px;color:#0f172a;letter-spacing:0.02em;margin-bottom:8px;">Redline Review PDF</div>`,
  );
  lines.push(`<div style="font-size:11px;color:#475569;margin-bottom:4px;">Generated by LawDog Review Export</div>`);
  lines.push(
    `<div style="font-size:11px;color:#334155;margin-bottom:8px;">${escapeHtml(formatAuditGeneratedLine(meta.generatedAt))}</div>`,
  );
  if (reviewer) {
    lines.push(`<div style="font-size:11px;color:#334155;"><span style="color:#64748b;">Reviewer:</span> ${escapeHtml(reviewer)}</div>`);
  }
  if (email) {
    lines.push(
      `<div style="font-size:10px;color:#64748b;word-break:break-all;margin-top:3px;">${escapeHtml(email)}</div>`,
    );
  }
  if (title) {
    lines.push(
      `<div style="font-size:11px;color:#334155;margin-top:8px;"><span style="color:#64748b;">Agreement:</span> ${escapeHtml(title)}</div>`,
    );
  }
  lines.push(
    `<div style="font-size:10px;color:#94a3b8;margin-top:8px;font-family:ui-monospace,Menlo,monospace;">ID: ${escapeHtml(meta.agreementId)}</div>`,
  );
  return `<header style="border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:0 0 22px;background:#f8fafc;">${lines.join("")}</header>`;
}

function normPdfBlockLabelKey(label: string): string {
  return label.replace(/\s+/g, " ").trim().toLowerCase();
}

function buildHumanStructuredPdfLead(s: HumanReviewStructuredForPdf): string {
  const esc = escapeHtml;
  const box =
    "margin:0 0 22px;padding:16px 18px;background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0;";
  let html = `<section style="${box}">`;
  html += `<p style="margin:0 0 12px;font-size:16px;font-weight:600;color:#0f172a;line-height:1.45;">${esc(s.headlinePlain)}</p>`;
  if (s.importantBullets.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Important changes</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:18px;font-size:14px;color:#0f172a;line-height:1.62;">`;
    for (const b of s.importantBullets) {
      html += `<li style="margin:0 0 6px;">${esc(b)}</li>`;
    }
    html += `</ul>`;
  }
  if (s.clarificationBullets.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Clarifications</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:18px;font-size:14px;color:#334155;line-height:1.62;">`;
    for (const b of s.clarificationBullets) {
      html += `<li style="margin:0 0 6px;">${esc(b)}</li>`;
    }
    html += `</ul>`;
  }
  if (s.negativeAssuranceLines.length > 0) {
    html += `<ul style="margin:0 0 14px;padding-left:16px;font-size:12px;color:#64748b;line-height:1.55;">`;
    for (const line of s.negativeAssuranceLines) {
      html += `<li style="margin:0 0 4px;">${esc(line)}</li>`;
    }
    html += `</ul>`;
  }
  html += `<p style="margin:0 0 4px;font-size:13px;font-weight:600;color:#0f172a;">${esc(s.confidenceHeadline)}</p>`;
  html += `<p style="margin:0 0 12px;font-size:12px;color:#475569;line-height:1.55;">${esc(s.confidenceBody)}</p>`;
  html += `<p style="margin:0;font-size:11px;color:#64748b;line-height:1.5;">${esc(s.nothingSentFootnote)}</p>`;
  html += `</section>`;
  return html;
}

/**
 * Renders one block as flowing paragraphs: consecutive insert/delete/same segments merge first,
 * then inline spans share `<p>` until a `\n\n` paragraph break (fixes token-slab / orphan-word PDF noise).
 */
function renderBlockInlineFlow(block: LegalRedlineBlock, opts?: { suppressSectionHeader?: boolean }): string {
  const merged = mergeAdjacentRedlineSegmentsAllTypes(block.segments);
  const label = (block.label || block.heading || block.clauseNumber || "").trim();
  const header =
    label && !opts?.suppressSectionHeader
      ? `<header style="margin:0 0 12px;padding-bottom:8px;border-bottom:1px solid #e2e8f0;"><p style="margin:0;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.04em;text-transform:uppercase;">${escapeHtml(
          label,
        )}</p></header>`
      : "";
  const shellStyle = block.hasChange
    ? "display:block;margin:0;padding:16px 0 18px 14px;border-left:3px solid #cbd5e1;"
    : "display:block;margin:0;padding:16px 0 18px;border-left:3px solid transparent;";

  /** One `<p>` flows across adjacent segments until `\n\n` forces a new paragraph. */
  let html = "";
  let inPara = false;

  for (const seg of merged) {
    const blocks = seg.text.split(/\n\n+/);
    for (let bi = 0; bi < blocks.length; bi++) {
      if (bi > 0) {
        if (inPara) {
          html += "</p>";
          inPara = false;
        }
      }
      if (!inPara) {
        html += `<p style="${P_STYLE}">`;
        inPara = true;
      }
      const raw = blocks[bi] ?? "";
      const lines = raw.split("\n");
      html += lines.map((ln) => spanForInlineSegment(seg.type, ln)).join("<br/>");
    }
  }
  if (inPara) {
    html += "</p>";
  }
  if (!html.trim()) {
    html = `<p style="${P_STYLE}"><span style="${SPAN_SAME}">\u00a0</span></p>`;
  }

  return `<section style="${shellStyle}">${header}${html}</section>`;
}

/**
 * Inline-styled HTML for PyMuPDF Story / server PDF (no Tailwind — classes are stripped server-side).
 * Uses merged segments + paragraph flow (not per-token block slabs).
 */
export type RecipientRedlinePdfHumanExtras = {
  /** Escaped HTML bullets or paragraphs (already safe), or plain text wrapped in <p>. */
  summaryHtml?: string | null;
  /** Plain text — escaped for appendix. */
  reviewerNotesPlain?: string | null;
  /** First-page human review (preferred over legacy {@link summaryHtml}). */
  structuredHumanReview?: HumanReviewStructuredForPdf | null;
  /** Optional short reference appendix (counts / reference only). */
  technicalAppendixPlain?: string | null;
};

export function buildRecipientRedlinePdfHtml(
  vm: LegalRedlineDocumentViewModel,
  audit?: RecipientRedlinePdfAuditMeta | null,
  human?: RecipientRedlinePdfHumanExtras | null,
): string {
  const auditBlock = audit ? buildAuditHeader({ ...audit, generatedAt: audit.generatedAt }) : "";
  let lead = "";
  const struct = human?.structuredHumanReview;
  if (struct && (struct.headlinePlain.trim() || struct.importantBullets.length > 0 || struct.clarificationBullets.length > 0)) {
    lead += buildHumanStructuredPdfLead(struct);
  } else {
    const sum = (human?.summaryHtml ?? "").trim();
    if (sum) {
      lead += `<section style="margin:0 0 22px;padding:14px 16px;background:#f1f5f9;border-radius:8px;border:1px solid #e2e8f0;"><p style="margin:0 0 8px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Summary</p><div style="font-size:14px;color:#0f172a;line-height:1.68;">${sum}</div></section>`;
    }
  }
  lead += `<h2 style="margin:0 0 14px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">A. Proposed agreement redline</h2>`;
  const seenLabels = new Set<string>();
  const sections = vm.blocks
    .map((b) => {
      const label = (b.label || b.heading || b.clauseNumber || "").trim();
      const key = normPdfBlockLabelKey(label);
      let suppress = false;
      if (label && seenLabels.has(key)) suppress = true;
      else if (label) seenLabels.add(key);
      return renderBlockInlineFlow(b, { suppressSectionHeader: suppress });
    })
    .join("");
  if (!sections.trim()) {
    return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px;">${auditBlock}${lead}<p style="margin:0;font:15px/1.65 Georgia,serif;color:#64748b;">No redline content.</p></article>`;
  }
  let appendix = "";
  const notes = (human?.reviewerNotesPlain ?? "").trim();
  if (notes) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">B. Reviewer notes — not part of agreement</h2><pre style="margin:0;font:13px/1.65 ui-sans-serif,system-ui;white-space:pre-wrap;color:#334155;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(notes)}</pre>`;
  }
  const tech = (human?.technicalAppendixPlain ?? "").trim();
  if (tech) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">C. Technical comparison (reference)</h2><pre style="margin:0;font:12px/1.6 ui-sans-serif,system-ui;white-space:pre-wrap;color:#475569;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(tech)}</pre>`;
  }
  return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px 28px;">${auditBlock}${lead}${sections}${appendix}</article>`;
}

export function sanitizeHtmlForRecipientPdfExport(html: string): string {
  return String(html ?? "").replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "");
}

/** Wrap read-tab / proposed snapshot HTML: typographic shell only (no redline). */
export function wrapRecipientVersionPdfHtml(innerHtml: string): string {
  const inner = sanitizeHtmlForRecipientPdfExport(innerHtml.trim());
  return `<article style="max-width:42rem;margin:0 auto;padding:16px 8px 28px;color:#0f172a;font:15px/1.72 Georgia,'Times New Roman',Times,serif;line-height:1.72;">${inner}</article>`;
}
