import { describe, expect, it } from "vitest";
import { recipientRecoverAgreementBodyFromPdfRawText } from "./recipientRevisedDraftExtractSanitize";
import { pdfImportPlainAfterSanitize } from "./recipientRevisedDraftImportText";

describe("recipientRecoverAgreementBodyFromPdfRawText", () => {
  it("recovers operative body when LawDog runners stripped the first sanitize pass", () => {
    const raw = [
      "Created with LawDog — Revised Draft for Review — Page 1",
      "",
      "WEB DEVELOPMENT AGREEMENT",
      "",
      "1. Services",
      "The Developer shall perform professional services.",
      "",
      "2. Payment",
      "Fees are Net 45 from invoice date.",
    ].join("\n");
    const r = recipientRecoverAgreementBodyFromPdfRawText(raw);
    expect(r.agreementText.toLowerCase()).toContain("net 45");
    expect(r.agreementText.toLowerCase()).toContain("web development");
    expect(r.agreementText.trim().length).toBeGreaterThan(60);
  });
});

describe("pdfImportPlainAfterSanitize + recovery contract", () => {
  it("thin first sanitize + raw with recoverable body yields useable agreement text length", () => {
    const raw = [
      "Generated by LawDog for QA",
      "",
      "Consulting Agreement",
      "",
      "1. Fees",
      "Client shall pay invoices within forty-five days.",
      "",
      "2. Term",
      "This agreement continues for one year unless terminated earlier with written notice.",
    ].join("\n");
    const san = { agreementText: "   ", reviewerNotes: null as string | null, artifactsRemoved: [] as string[] };
    const routed = pdfImportPlainAfterSanitize(raw, san);
    expect(routed.kind).toBe("use_raw_for_classification");
    const recovered = recipientRecoverAgreementBodyFromPdfRawText(raw);
    expect(recovered.agreementText.trim().length).toBeGreaterThanOrEqual(48);
  });
});
