import { describe, expect, it } from "vitest";
import type { LegalRedlineDocumentViewModel } from "./legalRedlineBlocks";
import { buildLegalRedlineDocumentViewModel, mergeAdjacentRedlineSegmentsAllTypes } from "./legalRedlineBlocks";
import {
  buildRecipientRedlinePdfHtml,
  sanitizeHtmlForRecipientPdfExport,
  wrapRecipientVersionPdfHtml,
} from "./recipientPreviewPdfHtml";

describe("mergeAdjacentRedlineSegmentsAllTypes", () => {
  it("merges consecutive insert and delete chains", () => {
    expect(
      mergeAdjacentRedlineSegmentsAllTypes([
        { type: "delete", text: "on receipt" },
        { type: "delete", text: " and late fees" },
        { type: "insert", text: "Net 30" },
      ]),
    ).toEqual([
      { type: "delete", text: "on receipt and late fees" },
      { type: "insert", text: "Net 30" },
    ]);
  });
});

describe("buildRecipientRedlinePdfHtml", () => {
  const auditTs = new Date(2026, 4, 6, 21, 24, 0);

  it("emits inline insert/delete styling without slab backgrounds per line token", () => {
    const vm = buildLegalRedlineDocumentViewModel("Fee is due on receipt.", "Fee is Net 30.");
    const html = buildRecipientRedlinePdfHtml(vm);
    expect(html.toUpperCase()).not.toContain("CLAW");
    expect(html).toMatch(/text-decoration:underline/i);
    expect(html).toMatch(/line-through/i);
    expect(html).toContain("<article");
    /** Flowing paragraph: multiple spans inside one <p> when no \\n\\n between segments */
    const pOpenCount = (html.match(/<p style=/g) ?? []).length;
    expect(pOpenCount).toBeGreaterThanOrEqual(1);
  });

  it("flows adjacent word-diff segments in shared paragraphs (fewer isolated slabs)", () => {
    const vm = buildLegalRedlineDocumentViewModel(
      "Payment is due on receipt. Late fees apply.",
      "Payment is Net 30. Late fees apply.",
    );
    const html = buildRecipientRedlinePdfHtml(vm);
    /** Should not explode into dozens of top-level block wrappers per micro-token */
    expect((html.match(/<\/p>/g) ?? []).length).toBeLessThan(80);
  });

  it("includes human summary and reviewer appendix when extras provided", () => {
    const vm = buildLegalRedlineDocumentViewModel("Fee is due on receipt.", "Fee is Net 30.");
    const html = buildRecipientRedlinePdfHtml(
      vm,
      {
        agreementId: "ag_x",
        agreementTitle: "T",
        reviewerDisplayName: "Sarah Collins",
        reviewerEmail: null,
        generatedAt: auditTs,
      },
      {
        summaryHtml: "<p>Focused edits to payment timing.</p><ul><li>Payment terms updated</li></ul>",
        reviewerNotesPlain: "Please confirm by Friday.",
      },
    );
    expect(html).toContain("Summary");
    expect(html).toContain("A. Proposed agreement redline");
    expect(html).toContain("B. Reviewer notes");
    expect(html).toContain("Please confirm by Friday.");
  });

  it("includes audit metadata when provided", () => {
    const vm = buildLegalRedlineDocumentViewModel("a", "b");
    const html = buildRecipientRedlinePdfHtml(vm, {
      agreementId: "ag_review_export",
      agreementTitle: "Web Development Agreement",
      reviewerDisplayName: "Sarah Collins",
      reviewerEmail: "sarah@example.com",
      generatedAt: auditTs,
    });
    expect(html).toContain("Redline Review PDF");
    expect(html).toContain("Generated by LawDog Review Export");
    expect(html).toContain("Reviewer:");
    expect(html).toContain("Sarah Collins");
    expect(html).toContain("sarah@example.com");
    expect(html).toContain("Agreement:");
    expect(html).toContain("Web Development Agreement");
    expect(html).toContain("ID: ag_review_export");
  });

  it("returns a minimal article when there are no blocks", () => {
    const html = buildRecipientRedlinePdfHtml({
      blocks: [],
      stats: {
        blockCount: 0,
        changedBlockCount: 0,
        insertCount: 0,
        deleteCount: 0,
        sameCount: 0,
        segmentCount: 0,
        currentLen: 0,
        proposedLen: 0,
      },
      hasChanges: false,
    });
    expect(html).toContain("No redline content.");
  });

  it("starts a new PDF paragraph when a segment contains \\n\\n", () => {
    const vm: LegalRedlineDocumentViewModel = {
      blocks: [
        {
          id: "single-block",
          kind: "paragraph",
          label: "Clause",
          segments: [{ type: "same", text: "First paragraph.\n\nSecond paragraph." }],
          insertCount: 0,
          deleteCount: 0,
          sameCount: 1,
          hasInsert: false,
          hasDelete: false,
          hasChange: false,
        },
      ],
      stats: {
        blockCount: 1,
        changedBlockCount: 0,
        insertCount: 0,
        deleteCount: 0,
        sameCount: 1,
        segmentCount: 1,
        currentLen: 0,
        proposedLen: 0,
      },
      hasChanges: false,
    };
    const html = buildRecipientRedlinePdfHtml(vm);
    expect(html).toMatch(/<\/p>\s*<p style=/);
  });
});

describe("wrapRecipientVersionPdfHtml + sanitize", () => {
  it("wraps clean versions without scripts", () => {
    const html = wrapRecipientVersionPdfHtml('<p onclick="evil()">Hi</p><script>x</script>');
    expect(html).not.toMatch(/<script/i);
    expect(html).toContain("article");
    expect(html).toContain("<p");
  });

  it("sanitize strips scripts", () => {
    expect(sanitizeHtmlForRecipientPdfExport('<p>x</p><script>1</script>')).not.toContain("<script");
  });

  it("does not use redline styling or audit header — original/proposed exports are single-version HTML only", () => {
    const html = wrapRecipientVersionPdfHtml("<p>Baseline agreement text only.</p>");
    expect(html).not.toMatch(/line-through/i);
    expect(html).not.toMatch(/Redline Review PDF/);
    expect(html).not.toMatch(/text-decoration:underline/i);
  });
});
