import { escapeHtml } from "../components/agreements/premiumAgreementDocumentHtml";
import type { LegalRedlineBlock, LegalRedlineDocumentViewModel, LegalRedlineSegment } from "./legalRedlineBlocks";
import { mergeAdjacentRedlineSegmentsAllTypes } from "./legalRedlineBlocks";
import type { RecipientCompareConfidenceLevel } from "./recipientCompareConfidence";
import {
  RECIPIENT_ADVANCED_REDLINE_INTRO,
  RECIPIENT_BUSINESS_REVIEW_MOST_IMPORTANT_HEADING,
  RECIPIENT_BUSINESS_REVIEW_NO_CHANGES_SECTION,
  RECIPIENT_BUSINESS_REVIEW_OTHER_EDITS_LINE,
  RECIPIENT_BUSINESS_REVIEW_RECOMMENDED_FOCUS_HEADING,
  RECIPIENT_EXPORT_PDF_ADVANCED_MARKUP_APPENDIX_HEADING,
  RECIPIENT_EXPORT_PDF_APPENDIX_EXTRACTED_NOTES_HEADING,
  RECIPIENT_EXPORT_PDF_APPENDIX_REFERENCE,
  RECIPIENT_EXPORT_PDF_CLEAN_PROPOSED_HEADING,
  RECIPIENT_EXPORT_PDF_KEY_CHANGED_WORDING_HEADING,
  RECIPIENT_EXPORT_PDF_NOT_RESTAT_APPENDIX_HEADING,
  RECIPIENT_EXPORT_PDF_SECTION_DETAILED_REDLINE,
  RECIPIENT_EXPORT_SECTION_SUBSTANTIALLY_REVISED,
  RECIPIENT_NOT_RESTAT_ORIGINAL_FOOTNOTE,
  RECIPIENT_SEMANTIC_PRIOR_LABEL,
  RECIPIENT_SEMANTIC_REDLINE_INTRO,
  RECIPIENT_SEMANTIC_REVISED_LABEL,
  RECIPIENT_SHOW_ADVANCED_LEGAL_MARKUP,
  RECIPIENT_SHOW_LINE_BY_LINE_MARKUP,
} from "./portableReviewCopy";
import {
  blockPriorAndRevisedPlain,
  recipientBlockEligibleForAdvancedLegalMarkup,
  type RecipientSemanticRedlinePresentation,
} from "./recipientWholeDocSemanticRender";
import type { HumanReviewStructuredForPdf } from "./recipientHumanReviewSummaryModel";
import { recipientBlockShowsRedline, recipientClauseMeaningfulMaterialRatio } from "./recipientMeaningfulRedlinePass";

export type RecipientPreviewPdfExportKind = "original" | "proposed" | "redline";

/** Audit strip for redline PDF exports (first-page header box). */
export type RecipientRedlinePdfAuditMeta = {
  agreementId: string;
  agreementTitle?: string | null;
  reviewerDisplayName?: string | null;
  reviewerEmail?: string | null;
  generatedAt: Date;
};

const P_STYLE =
  "margin:0 0 10px;line-height:1.58;font-size:15px;color:#0f172a;font-family:Georgia,'Times New Roman',Times,serif;text-align:left;";
/** Retained — readable body text */
const SPAN_SAME = `color:#0f172a;font:inherit;`;
/** Insertions — soft green emphasis (no slab blocks) */
const SPAN_INS = `color:#14532d;font:inherit;background:rgba(220,252,231,0.85);text-decoration:underline;text-decoration-color:#15803d;text-underline-offset:3px;padding:0 1px;border-radius:2px;`;
/** Deletions — soft rose strikethrough */
const SPAN_DEL = `color:#7f1d1d;font:inherit;text-decoration:line-through;text-decoration-color:rgba(190,18,60,0.45);background:rgba(255,241,242,0.65);padding:0 1px;border-radius:2px;`;

function spanForInlineSegment(type: LegalRedlineSegment["type"], line: string): string {
  const inner = escapeHtml(line.length ? line : "\u00a0");
  if (type === "same") return `<span style="${SPAN_SAME}">${inner}</span>`;
  if (type === "insert") return `<span style="${SPAN_INS}">${inner}</span>`;
  return `<span style="${SPAN_DEL}">${inner}</span>`;
}

function formatAuditGeneratedLine(d: Date): string {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone ?? "UTC";
    const main = new Intl.DateTimeFormat(undefined, {
      dateStyle: "medium",
      timeStyle: "short",
      timeZone: tz,
    }).format(d);
    const tzParts = new Intl.DateTimeFormat(undefined, {
      timeZoneName: "short",
      timeZone: tz,
    }).formatToParts(d);
    const tzName = tzParts.find((p) => p.type === "timeZoneName")?.value ?? "";
    return tzName ? `${main} ${tzName}` : main;
  } catch {
    return d.toISOString();
  }
}

function buildAuditHeader(meta: RecipientRedlinePdfAuditMeta): string {
  const title = (meta.agreementTitle || "").trim();
  const reviewer = (meta.reviewerDisplayName || "").trim();
  const email = (meta.reviewerEmail || "").trim();
  const lines: string[] = [];
  lines.push(
    `<div style="font-weight:600;font-size:13px;color:#0f172a;letter-spacing:0.02em;margin-bottom:8px;">Redline Review PDF</div>`,
  );
  lines.push(`<div style="font-size:11px;color:#475569;margin-bottom:4px;">Generated by LawDog Review Export</div>`);
  lines.push(
    `<div style="font-size:11px;color:#334155;margin-bottom:8px;">${escapeHtml(formatAuditGeneratedLine(meta.generatedAt))}</div>`,
  );
  if (reviewer) {
    lines.push(`<div style="font-size:11px;color:#334155;"><span style="color:#64748b;">Reviewer:</span> ${escapeHtml(reviewer)}</div>`);
  }
  if (email) {
    lines.push(
      `<div style="font-size:10px;color:#64748b;word-break:break-all;margin-top:3px;">${escapeHtml(email)}</div>`,
    );
  }
  if (title) {
    lines.push(
      `<div style="font-size:11px;color:#334155;margin-top:8px;"><span style="color:#64748b;">Agreement:</span> ${escapeHtml(title)}</div>`,
    );
  }
  lines.push(
    `<div style="font-size:10px;color:#94a3b8;margin-top:8px;font-family:ui-monospace,Menlo,monospace;">ID: ${escapeHtml(meta.agreementId)}</div>`,
  );
  return `<header style="border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;margin:0 0 22px;background:#f8fafc;">${lines.join("")}</header>`;
}

function normPdfBlockLabelKey(label: string): string {
  return label.replace(/\s+/g, " ").trim().toLowerCase();
}

/** Normalize block text for export dedupe (whitespace, punctuation noise, numbering). */
export function normalizeRedlineFingerprintForExport(raw: string): string {
  const t = raw.replace(/\r\n/g, "\n").toLowerCase();
  return t
    .replace(/[\u2018\u2019\u201c\u201d]/g, "'")
    .replace(/[^a-z0-9\s]+/gi, " ")
    .replace(/\s+/g, " ")
    .replace(/^\s*\d+(?:\.\d+)*[\.)]\s*/gm, "")
    .trim();
}

function normalizeFingerprintSafe(raw: string): string {
  return normalizeRedlineFingerprintForExport(raw);
}

function blockPlainTextForFingerprint(block: LegalRedlineBlock): string {
  const merged = mergeAdjacentRedlineSegmentsAllTypes(block.segments);
  return merged.map((s) => s.text).join("\n");
}

function blockIsDenseForExportCollapse(block: LegalRedlineBlock): boolean {
  if (!block.hasChange) return false;
  const changes = block.segments.filter((s) => s.type !== "same");
  if (changes.length >= 12) return true;
  if (changes.length >= 6 && changes.every((s) => String(s.text).length <= 56)) return true;
  return false;
}

const BOILERPLATE_FINGERPRINT_SUBSTRINGS = [
  "draft agreement",
  "non binding template",
  "web development agreement",
  "in witness whereof",
  "created with lawdog",
  "draft for review",
];

function looksLikeBoilerplateFingerprint(norm: string): boolean {
  if (norm.length < 24) return false;
  return BOILERPLATE_FINGERPRINT_SUBSTRINGS.some((s) => norm.includes(s));
}

function renderCollapsedExportSection(): string {
  const shellStyle =
    "display:block;margin:0;padding:14px 0 16px 14px;border-left:3px solid #e2e8f0;background:#f8fafc;";
  return `<section style="${shellStyle}"><p style="${P_STYLE}"><span style="${SPAN_SAME}">${escapeHtml(
    RECIPIENT_EXPORT_SECTION_SUBSTANTIALLY_REVISED,
  )}</span></p></section>`;
}

function buildHumanStructuredPdfLead(s: HumanReviewStructuredForPdf): string {
  const esc = escapeHtml;
  const box =
    "margin:0 0 22px;padding:16px 18px;background:#f8fafc;border-radius:8px;border:1px solid #e2e8f0;";
  let html = `<section style="${box}">`;
  html += `<p style="margin:0 0 12px;font-size:16px;font-weight:600;color:#0f172a;line-height:1.45;">${esc(s.headlinePlain)}</p>`;
  if ((s.recommendedFocusLines ?? []).length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_BUSINESS_REVIEW_RECOMMENDED_FOCUS_HEADING,
    )}</p>`;
    html += `<ol style="margin:0 0 10px;padding-left:20px;font-size:13px;color:#0f172a;line-height:1.55;">`;
    const focusLines = s.recommendedFocusLines ?? [];
    for (let i = 0; i < focusLines.length; i++) {
      html += `<li style="margin:0 0 4px;">${esc(focusLines[i]!)}</li>`;
    }
    html += `</ol>`;
    html += `<p style="margin:0 0 14px;font-size:12px;color:#475569;line-height:1.5;">${escapeHtml(RECIPIENT_BUSINESS_REVIEW_OTHER_EDITS_LINE)}</p>`;
  }
  if (s.importantBullets.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_BUSINESS_REVIEW_MOST_IMPORTANT_HEADING,
    )}</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:18px;font-size:14px;color:#0f172a;line-height:1.62;">`;
    for (const b of s.importantBullets) {
      html += `<li style="margin:0 0 6px;">${esc(b)}</li>`;
    }
    html += `</ul>`;
  }
  if (s.clarificationBullets.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Clarifications</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:18px;font-size:14px;color:#334155;line-height:1.62;">`;
    for (const b of s.clarificationBullets) {
      html += `<li style="margin:0 0 6px;">${esc(b)}</li>`;
    }
    html += `</ul>`;
  }
  if (s.negativeAssuranceLines.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_BUSINESS_REVIEW_NO_CHANGES_SECTION,
    )}</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:16px;font-size:12px;color:#64748b;line-height:1.55;">`;
    for (const line of s.negativeAssuranceLines) {
      html += `<li style="margin:0 0 4px;">${esc(line)}</li>`;
    }
    html += `</ul>`;
  }
  const ctxLines = (s.negotiationContextLines ?? []).map((l) => l.trim()).filter(Boolean).slice(0, 2);
  if (ctxLines.length > 0) {
    html += `<p style="margin:0 0 6px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Review context</p>`;
    html += `<ul style="margin:0 0 14px;padding-left:16px;font-size:12px;color:#334155;line-height:1.55;">`;
    for (const line of ctxLines) {
      html += `<li style="margin:0 0 4px;">${esc(line)}</li>`;
    }
    html += `</ul>`;
  }
  html += `<p style="margin:0 0 4px;font-size:13px;font-weight:600;color:#0f172a;">${esc(s.confidenceHeadline)}</p>`;
  html += `<p style="margin:0 0 12px;font-size:12px;color:#475569;line-height:1.55;">${esc(s.confidenceBody)}</p>`;
  html += `<p style="margin:0;font-size:11px;color:#64748b;line-height:1.5;">${esc(s.nothingSentFootnote)}</p>`;
  html += `</section>`;
  return html;
}

/**
 * Renders one block as flowing paragraphs: consecutive insert/delete/same segments merge first,
 * then inline spans share `<p>` until a `\n\n` paragraph break (fixes token-slab / orphan-word PDF noise).
 */
function renderBlockInlineFlow(block: LegalRedlineBlock, opts?: { suppressSectionHeader?: boolean }): string {
  const merged = mergeAdjacentRedlineSegmentsAllTypes(block.segments);
  const label = (block.label || block.heading || block.clauseNumber || "").trim();
  const header =
    label && !opts?.suppressSectionHeader
      ? `<header style="margin:0 0 12px;padding-bottom:8px;border-bottom:1px solid #e2e8f0;"><p style="margin:0;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.04em;text-transform:uppercase;">${escapeHtml(
          label,
        )}</p></header>`
      : "";
  const shellStyle = block.hasChange
    ? "display:block;margin:0;padding:16px 0 18px 14px;border-left:3px solid #cbd5e1;"
    : "display:block;margin:0;padding:16px 0 18px;border-left:3px solid transparent;";

  /** One `<p>` flows across adjacent segments until `\n\n` forces a new paragraph. */
  let html = "";
  let inPara = false;

  for (const seg of merged) {
    const blocks = seg.text.split(/\n\n+/);
    for (let bi = 0; bi < blocks.length; bi++) {
      if (bi > 0) {
        if (inPara) {
          html += "</p>";
          inPara = false;
        }
      }
      if (!inPara) {
        html += `<p style="${P_STYLE}">`;
        inPara = true;
      }
      const raw = blocks[bi] ?? "";
      const lines = raw.split("\n");
      html += lines.map((ln) => spanForInlineSegment(seg.type, ln)).join("<br/>");
    }
  }
  if (inPara) {
    html += "</p>";
  }
  if (!html.trim()) {
    html = `<p style="${P_STYLE}"><span style="${SPAN_SAME}">\u00a0</span></p>`;
  }

  return `<section style="${shellStyle}">${header}${html}</section>`;
}

function renderSemanticBeforeAfterPdfBlock(
  block: LegalRedlineBlock,
  opts?: { suppressSectionHeader?: boolean },
): string {
  const { prior, revised } = blockPriorAndRevisedPlain(block);
  const label = (block.label || block.heading || block.clauseNumber || "").trim();
  const header =
    label && !opts?.suppressSectionHeader
      ? `<header style="margin:0 0 12px;padding-bottom:8px;border-bottom:1px solid #e2e8f0;"><p style="margin:0;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.04em;text-transform:uppercase;">${escapeHtml(
          label,
        )}</p></header>`
      : "";
  const box =
    "flex:1 1 280px;min-width:0;margin:0;padding:12px 14px;border:1px solid #e2e8f0;border-radius:8px;background:#f8fafc;";
  const pair = `<div style="display:flex;flex-wrap:wrap;gap:14px;margin:0 0 12px;">
    <div style="${box}">
      <p style="margin:0 0 6px;font-size:10px;font-weight:600;color:#64748b;letter-spacing:0.04em;text-transform:uppercase;">${escapeHtml(
        RECIPIENT_SEMANTIC_PRIOR_LABEL,
      )}</p>
      <pre style="margin:0;font:13px/1.65 Georgia,serif;white-space:pre-wrap;color:#334155;">${escapeHtml(prior)}</pre>
    </div>
    <div style="${box.replace("#f8fafc", "#ecfdf5").replace("#e2e8f0", "#bbf7d0")}">
      <p style="margin:0 0 6px;font-size:10px;font-weight:600;color:#065f46;letter-spacing:0.04em;text-transform:uppercase;">${escapeHtml(
        RECIPIENT_SEMANTIC_REVISED_LABEL,
      )}</p>
      <pre style="margin:0;font:13px/1.65 Georgia,serif;white-space:pre-wrap;color:#064e3b;">${escapeHtml(revised)}</pre>
    </div>
  </div>`;
  const micro = recipientBlockEligibleForAdvancedLegalMarkup(block)
    ? `<details style="margin-top:4px;"><summary style="cursor:pointer;font-size:11px;font-weight:600;color:#0369a1;">${escapeHtml(
        RECIPIENT_SHOW_LINE_BY_LINE_MARKUP,
      )}</summary><div style="margin-top:10px;">${renderBlockInlineFlow(block, { suppressSectionHeader: true })}</div></details>`
    : "";
  return `<section style="display:block;margin:0;padding:16px 0 18px 14px;border-left:3px solid #cbd5e1;">${header}${pair}${micro}</section>`;
}

/**
 * Inline-styled HTML for PyMuPDF Story / server PDF (no Tailwind — classes are stripped server-side).
 * Uses merged segments + paragraph flow (not per-token block slabs).
 */
export type RecipientRedlinePdfHumanExtras = {
  /** Escaped HTML bullets or paragraphs (already safe), or plain text wrapped in <p>. */
  summaryHtml?: string | null;
  /** Plain text — escaped for appendix. */
  reviewerNotesPlain?: string | null;
  /** First-page human review (preferred over legacy {@link summaryHtml}). */
  structuredHumanReview?: HumanReviewStructuredForPdf | null;
  /** Optional short reference appendix (counts / reference only). */
  technicalAppendixPlain?: string | null;
  /**
   * When not `high`, export applies stronger dedupe and may collapse very noisy changed blocks
   * to avoid replaying duplicate agreement body in the PDF.
   */
  exportCompareConfidenceLevel?: RecipientCompareConfidenceLevel | null;
  /** Matches UI semantic negotiation panels for heavy whole-document rewrites. */
  semanticRedlinePresentation?: RecipientSemanticRedlinePresentation | null;
  /**
   * When true (default), export body lists changed blocks only (matches “Only changed sections” in UI).
   * Set false to include unchanged blocks (e.g. diagnostics).
   */
  exportRedlineChangedSectionsOnly?: boolean;
  /**
   * Condensed clean-revision export: human summary first, then clean proposed text and topic HTML,
   * with tracked markup in a collapsed appendix (does not read as “everything deleted”).
   */
  condensedCleanRevisionPdf?: {
    cleanProposedPlain: string;
    /** Pre-escaped HTML blocks for topic prior/revised cards. */
    topicSectionHtml: string;
    /** Pre-escaped `<ul>` or fragment for “not restated” appendix. */
    notRestatedAppendixHtml: string;
  } | null;
  /**
   * When the uploaded draft matches the sender’s current agreement (import no-op), emit a short
   * summary PDF instead of reusing any prior redline / human-review blocks.
   */
  importMaterialNoChange?: boolean;
};

/** Heuristic: omit reviewer-notes appendix when text largely repeats agreement body already in the redline. */
function buildRecipientRedlinePdfBlocksInnerHtml(
  vm: LegalRedlineDocumentViewModel,
  human: RecipientRedlinePdfHumanExtras | null | undefined,
): string {
  const exportLevel = human?.exportCompareConfidenceLevel ?? "high";
  const tightenExport = exportLevel !== "high";
  const wantsChangedOnly = human?.exportRedlineChangedSectionsOnly !== false;
  const hasAnyMeaningful = vm.blocks.some((b) => recipientBlockShowsRedline(b));
  const blocksForPdf =
    wantsChangedOnly && hasAnyMeaningful ? vm.blocks.filter((b) => recipientBlockShowsRedline(b)) : vm.blocks;
  const sem = human?.semanticRedlinePresentation ?? null;
  const seenLabels = new Set<string>();
  const seenContentFp = new Set<string>();
  const seenBoilerFp = new Set<string>();
  let denseCollapsedOnce = false;
  return blocksForPdf
    .map((b) => {
      const label = (b.label || b.heading || b.clauseNumber || "").trim();
      const key = normPdfBlockLabelKey(label);
      let suppress = false;
      if (label && seenLabels.has(key)) suppress = true;
      else if (label) seenLabels.add(key);

      const plainFp = blockPlainTextForFingerprint(b);
      const normFp = normalizeFingerprintSafe(plainFp);
      if (normFp.length >= 40) {
        if (seenContentFp.has(normFp)) {
          return "";
        }
        seenContentFp.add(normFp);
      }
      if (looksLikeBoilerplateFingerprint(normFp)) {
        if (seenBoilerFp.has(normFp)) {
          return "";
        }
        seenBoilerFp.add(normFp);
      }

      if (
        tightenExport &&
        exportLevel === "low" &&
        b.hasChange &&
        recipientBlockShowsRedline(b) &&
        blockIsDenseForExportCollapse(b)
      ) {
        if (!denseCollapsedOnce) {
          denseCollapsedOnce = true;
          return renderCollapsedExportSection();
        }
        return "";
      }

      if (sem?.blockStyle.get(b.id) === "before_after" && recipientBlockShowsRedline(b)) {
        return renderSemanticBeforeAfterPdfBlock(b, { suppressSectionHeader: suppress });
      }

      const flow = renderBlockInlineFlow(b, { suppressSectionHeader: suppress });
      if (b.hasChange && recipientBlockShowsRedline(b) && recipientBlockEligibleForAdvancedLegalMarkup(b)) {
        return `<details style="display:block;margin:0 0 18px;border:1px solid #e2e8f0;border-radius:8px;padding:10px 12px;background:#ffffff;"><summary style="cursor:pointer;font-size:11px;font-weight:600;color:#0369a1;">${escapeHtml(
          RECIPIENT_SHOW_ADVANCED_LEGAL_MARKUP,
        )}</summary><div style="margin-top:10px;">${flow}</div></details>`;
      }
      return flow;
    })
    .join("");
}

function buildCondensedCleanRevisionRedlinePdfArticle(
  vm: LegalRedlineDocumentViewModel,
  audit: RecipientRedlinePdfAuditMeta | null | undefined,
  human: RecipientRedlinePdfHumanExtras,
  cc: NonNullable<RecipientRedlinePdfHumanExtras["condensedCleanRevisionPdf"]>,
): string {
  const auditBlock = audit ? buildAuditHeader({ ...audit, generatedAt: audit.generatedAt }) : "";
  let lead = "";
  const struct = human.structuredHumanReview;
  if (struct && (struct.headlinePlain.trim() || struct.importantBullets.length > 0 || struct.clarificationBullets.length > 0)) {
    lead += buildHumanStructuredPdfLead(struct);
  } else {
    const sum = (human.summaryHtml ?? "").trim();
    if (sum) {
      lead += `<section style="margin:0 0 22px;padding:14px 16px;background:#f1f5f9;border-radius:8px;border:1px solid #e2e8f0;"><p style="margin:0 0 8px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Summary</p><div style="font-size:14px;color:#0f172a;line-height:1.68;">${sum}</div></section>`;
    }
  }
  const sections = buildRecipientRedlinePdfBlocksInnerHtml(vm, human);
  const advanced =
    sections.trim().length > 0
      ? `<details style="margin:24px 0;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#ffffff;"><summary style="cursor:pointer;font-size:12px;font-weight:600;color:#0f172a;">${escapeHtml(
          RECIPIENT_EXPORT_PDF_ADVANCED_MARKUP_APPENDIX_HEADING,
        )}</summary><p style="margin:12px 0 16px;font-size:12px;color:#475569;line-height:1.58;">${escapeHtml(
          RECIPIENT_ADVANCED_REDLINE_INTRO,
        )}</p>${sections}</details>`
      : "";
  const clean = escapeHtml(cc.cleanProposedPlain);
  const notRestated = `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
    RECIPIENT_EXPORT_PDF_NOT_RESTAT_APPENDIX_HEADING,
  )}</h2><p style="margin:0 0 10px;font-size:12px;color:#475569;line-height:1.55;">${escapeHtml(
    RECIPIENT_NOT_RESTAT_ORIGINAL_FOOTNOTE,
  )}</p>${cc.notRestatedAppendixHtml}`;
  let appendix = "";
  const notes = (human.reviewerNotesPlain ?? "").trim();
  if (notes && !notesShouldOmitExtractedAppendix(notes, vm, cc.cleanProposedPlain)) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_EXPORT_PDF_APPENDIX_EXTRACTED_NOTES_HEADING,
    )}</h2><pre style="margin:0;font:13px/1.65 ui-sans-serif,system-ui;white-space:pre-wrap;color:#334155;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(notes)}</pre>`;
  }
  const tech = (human.technicalAppendixPlain ?? "").trim();
  if (tech) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_EXPORT_PDF_APPENDIX_REFERENCE,
    )}</h2><pre style="margin:0;font:12px/1.6 ui-sans-serif,system-ui;white-space:pre-wrap;color:#475569;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(tech)}</pre>`;
  }
  return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px 28px;">${auditBlock}${lead}<h2 style="margin:22px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
    RECIPIENT_EXPORT_PDF_CLEAN_PROPOSED_HEADING,
  )}</h2><pre style="margin:0 0 22px;font:14px/1.72 Georgia,serif;white-space:pre-wrap;color:#0f172a;border:1px solid #e2e8f0;border-radius:8px;padding:14px 16px;background:#fafafa;">${clean}</pre><h2 style="margin:0 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
    RECIPIENT_EXPORT_PDF_KEY_CHANGED_WORDING_HEADING,
  )}</h2><div style="margin:0 0 8px;">${cc.topicSectionHtml}</div>${advanced}${notRestated}${appendix}</article>`;
}

export function notesLikelyDuplicateAgreementBodyForExport(notes: string, vm: LegalRedlineDocumentViewModel): boolean {
  /** Include both sides so pasted notes that match the prior draft still match when the redline is proposed-forward. */
  const body = vm.blocks
    .map((b) => `${b.currentText ?? ""}\n${b.proposedText ?? ""}`)
    .join("\n\n")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
  const nt = notes.replace(/\s+/g, " ").trim().toLowerCase();
  if (nt.length < 280 || body.length < 400) return false;
  const probe = nt.slice(0, Math.min(900, nt.length));
  return body.includes(probe.slice(0, 400));
}

function tokenSetForNotesDedupe(s: string): Set<string> {
  return new Set(
    s
      .replace(/\s+/g, " ")
      .trim()
      .toLowerCase()
      .split(" ")
      .map((w) => w.replace(/[^a-z0-9]/g, ""))
      .filter((w) => w.length > 2),
  );
}

/**
 * When “reviewer notes” are mostly the same text as the proposed draft (common mis-extract), omit notes appendix.
 */
export function notesLikelyDuplicateProposedPlain(notes: string, proposedPlain: string): boolean {
  const n = String(notes ?? "").replace(/\s+/g, " ").trim().toLowerCase();
  const p = String(proposedPlain ?? "").replace(/\s+/g, " ").trim().toLowerCase();
  if (n.length < 200 || p.length < 200) return false;
  const A = tokenSetForNotesDedupe(n);
  const B = tokenSetForNotesDedupe(p);
  if (A.size === 0 || B.size === 0) return false;
  let inter = 0;
  for (const w of A) {
    if (B.has(w)) inter++;
  }
  const union = A.size + B.size - inter;
  const jaccard = union === 0 ? 0 : inter / union;
  const lenR = Math.min(n.length, p.length) / Math.max(n.length, p.length);
  return jaccard >= 0.78 && lenR >= 0.65;
}

function recipientRedlineVmProposedPlainFingerprint(vm: LegalRedlineDocumentViewModel): string {
  return vm.blocks
    .map((b) => {
      const pt = String(b.proposedText ?? "").trim();
      if (pt) return pt;
      return b.segments
        .filter((s) => s.type !== "delete")
        .map((s) => s.text)
        .join("");
    })
    .join("\n\n");
}

export function notesShouldOmitExtractedAppendix(
  notes: string,
  vm: LegalRedlineDocumentViewModel,
  proposedPlainForDedupe?: string | null,
): boolean {
  const t = String(notes ?? "").trim();
  if (!t) return true;
  if (notesLikelyDuplicateAgreementBodyForExport(t, vm)) return true;
  const prop = (proposedPlainForDedupe ?? "").trim() || recipientRedlineVmProposedPlainFingerprint(vm);
  if (prop.length >= 180 && notesLikelyDuplicateProposedPlain(t, prop)) return true;
  return false;
}

export const RECIPIENT_IMPORT_NO_CHANGE_REDACT_PDF_HEADLINE = "No changes detected";

/** Minimal redline PDF for import matches current draft — no diff sections or human-review metrics. */
export function buildRecipientImportNoChangeRedlinePdfHtml(audit?: RecipientRedlinePdfAuditMeta | null): string {
  const auditBlock = audit ? buildAuditHeader({ ...audit, generatedAt: audit.generatedAt }) : "";
  const para = escapeHtml(
    "The uploaded draft matches the sender's current agreement after routine PDF cleanup (headers, footers, and spacing). This export intentionally omits detailed redline sections.",
  );
  const body = `<section style="margin:0 0 18px;padding:16px 18px;background:#ecfdf5;border-radius:8px;border:1px solid #a7f3d0;"><p style="margin:0 0 8px;font-size:15px;font-weight:600;color:#065f46;">${escapeHtml(
    RECIPIENT_IMPORT_NO_CHANGE_REDACT_PDF_HEADLINE,
  )}</p><p style="margin:0;font-size:14px;line-height:1.65;color:#0f172a;">${para}</p></section>`;
  return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px 28px;">${auditBlock}${body}</article>`;
}

export function buildRecipientRedlinePdfHtml(
  vm: LegalRedlineDocumentViewModel,
  audit?: RecipientRedlinePdfAuditMeta | null,
  human?: RecipientRedlinePdfHumanExtras | null,
): string {
  if (human?.importMaterialNoChange) {
    return buildRecipientImportNoChangeRedlinePdfHtml(audit ?? null);
  }
  const cc = human?.condensedCleanRevisionPdf;
  if (cc && String(cc.cleanProposedPlain ?? "").trim() && human) {
    return buildCondensedCleanRevisionRedlinePdfArticle(vm, audit, human, cc);
  }
  const auditBlock = audit ? buildAuditHeader({ ...audit, generatedAt: audit.generatedAt }) : "";
  let lead = "";
  const struct = human?.structuredHumanReview;
  if (struct && (struct.headlinePlain.trim() || struct.importantBullets.length > 0 || struct.clarificationBullets.length > 0)) {
    lead += buildHumanStructuredPdfLead(struct);
  } else {
    const sum = (human?.summaryHtml ?? "").trim();
    if (sum) {
      lead += `<section style="margin:0 0 22px;padding:14px 16px;background:#f1f5f9;border-radius:8px;border:1px solid #e2e8f0;"><p style="margin:0 0 8px;font-size:11px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">Summary</p><div style="font-size:14px;color:#0f172a;line-height:1.68;">${sum}</div></section>`;
    }
  }
  lead += `<h2 style="margin:0 0 14px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
    RECIPIENT_EXPORT_PDF_SECTION_DETAILED_REDLINE,
  )}</h2>`;
  const sem = human?.semanticRedlinePresentation ?? null;
  if (
    sem?.mode === "whole_section_replacement" &&
    !sem.shortRevisedVsLongBaseline &&
    recipientClauseMeaningfulMaterialRatio(vm) >= 0.6
  ) {
    lead += `<p style="margin:-6px 0 18px;font-size:12px;color:#475569;line-height:1.55;">${escapeHtml(
      RECIPIENT_SEMANTIC_REDLINE_INTRO,
    )}</p>`;
  }
  const sections = buildRecipientRedlinePdfBlocksInnerHtml(vm, human);
  if (!sections.trim()) {
    return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px;">${auditBlock}${lead}<p style="margin:0;font:15px/1.65 Georgia,serif;color:#64748b;">No redline content.</p></article>`;
  }
  let appendix = "";
  const notes = (human?.reviewerNotesPlain ?? "").trim();
  if (notes && !notesShouldOmitExtractedAppendix(notes, vm, null)) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_EXPORT_PDF_APPENDIX_EXTRACTED_NOTES_HEADING,
    )}</h2><pre style="margin:0;font:13px/1.65 ui-sans-serif,system-ui;white-space:pre-wrap;color:#334155;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(notes)}</pre>`;
  }
  const tech = (human?.technicalAppendixPlain ?? "").trim();
  if (tech) {
    appendix += `<h2 style="margin:28px 0 12px;font-size:12px;font-weight:600;color:#475569;letter-spacing:0.06em;text-transform:uppercase;">${escapeHtml(
      RECIPIENT_EXPORT_PDF_APPENDIX_REFERENCE,
    )}</h2><pre style="margin:0;font:12px/1.6 ui-sans-serif,system-ui;white-space:pre-wrap;color:#475569;border:1px solid #e2e8f0;border-radius:8px;padding:12px 14px;background:#fafafa;">${escapeHtml(tech)}</pre>`;
  }
  return `<article style="max-width:42rem;margin:0 auto;padding:12px 8px 28px;">${auditBlock}${lead}${sections}${appendix}</article>`;
}

export function sanitizeHtmlForRecipientPdfExport(html: string): string {
  return String(html ?? "").replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, "");
}

/** Wrap read-tab / proposed snapshot HTML: typographic shell only (no redline). */
export function wrapRecipientVersionPdfHtml(innerHtml: string): string {
  const inner = sanitizeHtmlForRecipientPdfExport(innerHtml.trim());
  return `<article style="max-width:42rem;margin:0 auto;padding:16px 8px 28px;color:#0f172a;font:15px/1.72 Georgia,'Times New Roman',Times,serif;line-height:1.72;">${inner}</article>`;
}
