/**
 * Batch QA fixtures — 35+ agreement archetypes for operational synthesis stress tests.
 */

import type { AgreementFamily } from "../agreementFamilyRouter";
import { definedShortNameFromLegalEntity } from "../paidProAgreementPolish";
import type { IntakePaymentField } from "../intakeCurrencyParse";

export type ProOperationalQaFixture = {
  id: string;
  label: string;
  archetype: string;
  intake: string;
  title: string;
  jurisdiction: string;
  purpose: string;
  paymentTerms: string;
  parties: string[];
  shortNames: string[];
  emails: string[];
  roles?: string[];
  duration?: string | null;
  dueDate?: string | null;
  effectiveDate?: string | null;
  payment?: IntakePaymentField;
  additionalTerms?: string | null;
  agreementFamily?: AgreementFamily;
  expectedSignals: RegExp[];
  expectMilestoneTable?: boolean;
  minSignalHits?: number;
  injectJunkRecitalParties?: string[];
};

function twoParty(
  id: string,
  label: string,
  archetype: string,
  vendor: string,
  client: string,
  vendorShort: string,
  clientShort: string,
  body: string,
  signals: RegExp[],
  extra?: Partial<ProOperationalQaFixture>,
): ProOperationalQaFixture {
  const vendorEmail = `ops@${vendorShort.toLowerCase().replace(/\s+/g, "")}.com`;
  const clientEmail = `legal@${clientShort.toLowerCase().replace(/\s+/g, "")}.com`;
  const parties = [vendor, client];
  return {
    id,
    label,
    archetype,
    parties,
    shortNames: parties.map((p) => definedShortNameFromLegalEntity(p)),
    emails: [vendorEmail, clientEmail],
    roles: ["Provider", "Client"],
    title: label,
    jurisdiction: extra?.jurisdiction ?? "Delaware",
    purpose: body.slice(0, 280),
    paymentTerms: extra?.paymentTerms ?? "Fees and invoicing per the intake schedule.",
    intake: `Agreement between ${vendor} and ${client}. ${body} Contact: ${vendorEmail} and ${clientEmail}. Governing law: ${extra?.jurisdiction ?? "Delaware"}.`,
    expectedSignals: signals,
    ...extra,
  };
}

function multiParty(
  id: string,
  label: string,
  archetype: string,
  parties: string[],
  shortNames: string[],
  body: string,
  signals: RegExp[],
  extra?: Partial<ProOperationalQaFixture>,
): ProOperationalQaFixture {
  const emails = shortNames.map((s, i) => `lead${i + 1}@${s.toLowerCase().replace(/\s+/g, "")}.io`);
  return {
    id,
    label,
    archetype,
    parties,
    shortNames: parties.map((p) => definedShortNameFromLegalEntity(p)),
    emails,
    title: label,
    jurisdiction: extra?.jurisdiction ?? "Delaware",
    purpose: body.slice(0, 320),
    paymentTerms: extra?.paymentTerms ?? "Milestone payments upon written acceptance.",
    intake: `Agreement among ${parties.join(", ")}. ${body} Contacts: ${emails.join(", ")}.`,
    expectedSignals: signals,
    ...extra,
  };
}

export const PRO_OPERATIONAL_QA_FIXTURES: readonly ProOperationalQaFixture[] = [
  twoParty(
    "01_saas_subscription",
    "SaaS Subscription Agreement",
    "vendor_saas",
    "Nimbus Cloud Systems LLC",
    "Orchard Retail Group Inc.",
    "Nimbus",
    "Orchard",
    "Nimbus provides a hosted SaaS subscription platform with API access, 99.9% uptime target, security patches, and monthly subscription billing. Orchard may not reverse engineer the service. Data processing and subprocessors require written approval.",
    [/saas|subscription|api|uptime|platform/i],
    { agreementFamily: "services_agreement" },
  ),
  twoParty(
    "02_master_services",
    "Master Services Agreement",
    "managed_services",
    "Helix Professional Services LLC",
    "Summit Manufacturing Inc.",
    "Helix",
    "Summit",
    "Helix will perform professional services under statements of work. Each SOW defines deliverables, acceptance criteria, and fees. Change orders require written approval.",
    [/master\s+services|statement\s+of\s+work|deliverable|acceptance/i],
  ),
  twoParty(
    "03_statement_of_work",
    "Statement of Work",
    "contractor_services",
    "Pixel Foundry LLC",
    "Beacon Brands Inc.",
    "Pixel Foundry",
    "Beacon",
    "Statement of Work for Phase 1 website rebuild: discovery, wireframes, development, UAT, and launch. Milestone payments tied to acceptance testing.",
    [/statement\s+of\s+work|milestone|acceptance|deliverable/i],
    {
      expectMilestoneTable: true,
      paymentTerms: "Milestone schedule: 40% kickoff, 30% UAT, 30% launch acceptance.",
    },
  ),
  twoParty(
    "04_consulting",
    "Consulting Agreement",
    "contractor_services",
    "Alder Advisory Partners LLC",
    "Crescent Holdings Corp.",
    "Alder",
    "Crescent",
    "Alder provides strategy consulting: market analysis, operating model design, and board-ready reporting. Monthly retainer with expense reimbursement.",
    [/consulting|advisory|retainer|deliverable/i],
  ),
  twoParty(
    "05_contractor",
    "Independent Contractor Agreement",
    "contractor_services",
    "Jordan Ellis",
    "Lumen Apps Inc.",
    "Jordan Ellis",
    "Lumen",
    "Jordan Ellis performs software engineering services as an independent contractor. Lumen owns work product upon payment. No benefits or employment relationship.",
    [/contractor|independent|deliverable|work\s+product/i],
    { jurisdiction: "California" },
  ),
  twoParty(
    "06_nda_mutual",
    "Mutual NDA",
    "nda_confidentiality",
    "Vantage Labs LLC",
    "Keystone Biotech Inc.",
    "Vantage",
    "Keystone",
    "Mutual confidentiality agreement for evaluating a potential collaboration. Each party may disclose Confidential Information for 24 months. Return or destroy on request.",
    [/mutual|confidential|non[-\s]?disclosure|nda/i],
    { agreementFamily: "nda" },
  ),
  twoParty(
    "07_nda_oneway",
    "One-Way NDA",
    "nda_confidentiality",
    "NovaForge Inc.",
    "Harbor Media LLC",
    "NovaForge",
    "Harbor",
    "NovaForge (Disclosing Party) shares product roadmap and pricing with Harbor (Receiving Party). Harbor may use information only to evaluate a partnership.",
    [/disclosing|receiving|confidential|non[-\s]?disclosure/i],
    { agreementFamily: "nda" },
  ),
  twoParty(
    "08_marketing_services",
    "Marketing Services Agreement",
    "generic_commercial",
    "BrightLoop Agency LLC",
    "PureSkin Commerce Inc.",
    "BrightLoop",
    "PureSkin",
    "BrightLoop runs paid social, email, and creative production. Client approves budgets and ad copy. Agency provides weekly performance reporting and FTC-compliant claims review.",
    [/marketing|advertising|campaign|reporting|ftc/i],
  ),
  twoParty(
    "09_software_development",
    "Software Development Agreement",
    "contractor_services",
    "Stackwright Dev LLC",
    "Finley Payments Corp.",
    "Stackwright",
    "Finley",
    "Custom payment portal development with agile sprints, milestone-based payments on UAT acceptance, code repository access, and warranty support. Source code escrow upon final payment.",
    [/software|development|deliverable|acceptance|source\s+code|milestone/i],
    { expectMilestoneTable: true, paymentTerms: "Milestone schedule: 40% kickoff, 30% UAT, 30% launch acceptance." },
  ),
  twoParty(
    "10_ai_implementation",
    "AI Implementation Agreement",
    "vendor_saas",
    "Cortex Automations LLC",
    "Metro Logistics Inc.",
    "Cortex",
    "Metro",
    "Cortex deploys enterprise AI workflow automation: model integration, prompt governance, human review gates, and monitoring. Customer data must not be used to train public models.",
    [/ai|model|workflow|automation|data/i],
  ),
  twoParty(
    "11_data_processing_addendum",
    "Data Processing Addendum",
    "vendor_saas",
    "Relay Cloud Services LLC",
    "HealthPath Clinics P.A.",
    "Relay",
    "HealthPath",
    "Processor processes personal data on behalf of Controller. Subprocessors require notice. Security measures, breach notification within 72 hours, and data subject request assistance.",
    [/processing|personal\s+data|subprocessor|breach|security/i],
  ),
  twoParty(
    "12_vendor",
    "Vendor Agreement",
    "generic_commercial",
    "SupplyCore Distribution LLC",
    "Atlas Restaurants Group Inc.",
    "SupplyCore",
    "Atlas",
    "SupplyCore supplies kitchen equipment and replacement parts under purchase orders. Delivery SLAs, inspection rights, and limited warranty on goods.",
    [/vendor|supply|purchase|delivery|warranty/i],
  ),
  twoParty(
    "13_reseller",
    "Reseller Agreement",
    "reseller",
    "Orbit Software LLC",
    "ChannelPeak Partners Inc.",
    "Orbit",
    "ChannelPeak",
    "ChannelPeak resells Orbit SaaS in North America with approved pricing, lead registration, and white-label sales collateral. Revenue share and quarterly true-up.",
    [/reseller|resale|channel|white[-\s]?label|revenue/i],
  ),
  twoParty(
    "14_referral_affiliate",
    "Referral and Affiliate Agreement",
    "reseller",
    "GrowthPilot LLC",
    "SignalMetrics Inc.",
    "GrowthPilot",
    "SignalMetrics",
    "GrowthPilot refers qualified enterprise leads. SignalMetrics pays 15% referral commission on collected revenue for 12 months with audit rights and anti-circumvention.",
    [/referral|affiliate|commission|revenue|audit/i],
  ),
  twoParty(
    "15_joint_venture",
    "Joint Venture Collaboration",
    "joint_venture",
    "Apex Robotics LLC",
    "Horizon Mobility Inc.",
    "Apex",
    "Horizon",
    "Parties co-develop autonomous warehouse robotics pilots with shared IP, joint steering committee, and phased commercialization milestones.",
    [/joint|collaboration|co[-\s]?develop|steering|milestone/i],
    { expectMilestoneTable: true },
  ),
  multiParty(
    "16_multi_party_rollout",
    "Multi-Party Project Rollout",
    "multi_party_implementation_consortium",
    [
      "Ironclad Systems Group LLC",
      "Harborline Data Solutions Inc.",
      "Northwind Automation Partners LLC",
      "Silver Mesa Analytics LP",
      "VertexGrid Technologies LLC",
    ],
    ["Ironclad", "Harborline", "Northwind", "Silver Mesa", "VertexGrid"],
    "Joint AI software and infrastructure rollout. Ironclad provides white-label workflow provisioning. Harborline leads migration and API integration. Milestone payments upon phase acceptance.",
    [/rollout|implementation|among|governance|milestone|white[-\s]?label/i],
    {
      expectMilestoneTable: true,
      paymentTerms: "Milestone invoicing per implementation schedule.",
    },
  ),
  twoParty(
    "17_equipment_lease",
    "Equipment Lease",
    "generic_commercial",
    "Premier Capital Leasing LLC",
    "Ridgeline Construction Inc.",
    "Premier Capital",
    "Ridgeline",
    "Lessor leases excavators and generators for 36 months with maintenance option, insurance requirements, and purchase option at end of term.",
    [/lease|equipment|rental|maintenance|term/i],
  ),
  twoParty(
    "18_content_licensing",
    "Content Licensing Agreement",
    "licensing",
    "Studio Lumen LLC",
    "StreamNow Media Inc.",
    "Studio Lumen",
    "StreamNow",
    "Licensor grants non-exclusive streaming rights for catalog content with territory limits, royalty statements, and takedown cooperation.",
    [/license|content|royalt|streaming|territory/i],
  ),
  twoParty(
    "19_influencer_sponsorship",
    "Influencer Sponsorship Agreement",
    "generic_commercial",
    "CreatorWave Talent LLC",
    "Glow Botanicals Inc.",
    "CreatorWave",
    "Glow Botanicals",
    "Creator delivers sponsored posts and short-form video with FTC disclosures, brand approval, usage rights for paid ads for 6 months, and competitor exclusivity.",
    [/influencer|sponsor|creator|ftc|deliverable/i],
  ),
  twoParty(
    "20_event_services",
    "Event Services Agreement",
    "generic_commercial",
    "Summit Events Co. LLC",
    "Pacific Biotech Inc.",
    "Summit Events",
    "Pacific Biotech",
    "Event production for annual user conference: venue, A/V, staffing, run-of-show, and cancellation terms with force majeure.",
    [/event|venue|production|cancellation/i],
  ),
  twoParty(
    "21_construction_services",
    "Construction Services Agreement",
    "generic_commercial",
    "Granite Ridge Builders LLC",
    "Oakwood Development LP",
    "Granite Ridge",
    "Oakwood",
    "Commercial tenant improvement with fixed fee, change order process, lien waivers, and substantial completion inspections.",
    [/construction|change\s+order|lien|completion/i],
  ),
  twoParty(
    "22_property_management",
    "Property Management Agreement",
    "managed_services",
    "UrbanKey Property Management LLC",
    "Lakeside Retail REIT Inc.",
    "UrbanKey",
    "Lakeside",
    "Manager operates retail centers: leasing support, maintenance vendors, CAM reconciliations, and monthly owner reporting.",
    [/property\s+management|tenant|maintenance|cam|reporting/i],
  ),
  twoParty(
    "23_commercial_lease_loi",
    "Commercial Lease Letter of Intent",
    "generic_commercial",
    "Harbor Point Realty LLC",
    "FreshBite Restaurants Inc.",
    "Harbor Point",
    "FreshBite",
    "Non-binding LOI for 5-year premises lease: base rent, TI allowance, options to renew, and exclusivity for café use.",
    [/letter\s+of\s+intent|lease|premises|rent|renewal/i],
  ),
  twoParty(
    "24_purchase_agreement",
    "Asset Purchase Agreement",
    "generic_commercial",
    "Northline Components LLC",
    "Volt Assembly Inc.",
    "Northline",
    "Volt",
    "Purchase of inventory and tooling with closing deliverables, reps and warranties, indemnity cap, and escrow holdback.",
    [/purchase|sale|closing|indemn|escrow/i],
  ),
  twoParty(
    "25_settlement",
    "Settlement Agreement",
    "generic_commercial",
    "Riley Chen",
    "Copper Street Labs Inc.",
    "Riley Chen",
    "Copper Street",
    "Parties settle disputed consulting invoices with mutual release, confidentiality of terms, and dismissal of claims.",
    [/settlement|release|claims|confidential/i],
  ),
  twoParty(
    "26_employment_offer",
    "Employment Offer Agreement",
    "generic_commercial",
    "Pioneer Analytics Inc.",
    "Taylor Morgan",
    "Pioneer",
    "Taylor Morgan",
    "At-will employment offer with base salary, annual bonus target, equity grant, benefits eligibility, and proprietary information assignment.",
    [/employment|offer|salary|benefits|proprietary/i],
    { jurisdiction: "New York" },
  ),
  twoParty(
    "27_separation",
    "Separation Agreement",
    "generic_commercial",
    "Pioneer Analytics Inc.",
    "Taylor Morgan",
    "Pioneer",
    "Taylor Morgan",
    "Separation with severance, COBRA assistance, return of company property, and general release of claims.",
    [/separation|severance|release|claims/i],
  ),
  twoParty(
    "28_ip_assignment",
    "IP Assignment Agreement",
    "licensing",
    "Inventive Labs LLC",
    "Quantum Devices Corp.",
    "Inventive",
    "Quantum",
    "Assignor assigns all right, title, and interest in listed patents and software inventions with moral rights waiver where permitted.",
    [/assign|intellectual\s+property|invention|patent|ownership/i],
  ),
  twoParty(
    "29_beta_testing",
    "Beta Testing Agreement",
    "vendor_saas",
    "Launchpad QA LLC",
    "NexGen Fintech Inc.",
    "Launchpad",
    "NexGen",
    "Beta access to pre-release software for feedback and bug reports. No production SLA. Feedback license granted to provider.",
    [/beta|testing|feedback|pre[-\s]?release/i],
  ),
  twoParty(
    "30_maintenance_support",
    "Maintenance and Support Agreement",
    "managed_services",
    "SteadyOps Support LLC",
    "Clearwater ERP Inc.",
    "SteadyOps",
    "Clearwater",
    "Annual maintenance with severity-based response times, patch delivery, and uptime credits for critical incidents.",
    [/maintenance|support|sla|uptime|response/i],
  ),
  twoParty(
    "31_revenue_share",
    "Revenue Share Agreement",
    "reseller",
    "PayForge LLC",
    "MarketHub Collective Inc.",
    "PayForge",
    "MarketHub",
    "Parties split net collected revenue 60/40 with monthly statements, chargeback adjustments, and audit rights.",
    [/revenue\s+share|split|collections|audit/i],
  ),
  twoParty(
    "32_white_label_platform",
    "White-Label Platform Agreement",
    "reseller",
    "Ironclad Systems Group LLC",
    "Harborline Data Solutions Inc.",
    "Ironclad",
    "Harborline",
    "Ironclad provides white-label AI workflow platform, core maintenance, and branding controls. Harborline implements customer rollouts with milestone-based go-live gates and tier-1 support.",
    [/white[-\s]?label|platform|branding|workflow|maintenance|milestone/i],
    { expectMilestoneTable: true, paymentTerms: "Milestone schedule: 40% platform access, 30% branding QA, 30% production go-live." },
  ),
  twoParty(
    "33_managed_services",
    "Managed Services Agreement",
    "managed_services",
    "OperateNow MSP LLC",
    "SecureGov Agency Inc.",
    "OperateNow",
    "SecureGov",
    "24x7 managed infrastructure operations, runbooks, incident response, and quarterly service reviews with defined SLAs.",
    [/managed\s+services|msp|runbook|incident|sla/i],
  ),
  twoParty(
    "34_loan_promissory",
    "Loan / Promissory Note",
    "generic_commercial",
    "Redwood Lending LLC",
    "Blue Harbor Imports Inc.",
    "Redwood",
    "Blue Harbor",
    "Principal loan of $250,000 with 8% annual interest, monthly installments, prepayment permitted, and default remedies.",
    [/loan|principal|interest|repayment|installment/i],
    {
      payment: { amount: 250_000, cadence: "monthly", valid: true },
      paymentTerms: "Principal $250,000; monthly installments per amortization schedule.",
    },
  ),
  twoParty(
    "35_membership_partner",
    "Membership / Community Partner Agreement",
    "generic_commercial",
    "Guild Collective LLC",
    "Riverstone Co-Working Inc.",
    "Guild",
    "Riverstone",
    "Community partner tier with event hosting rights, member referral fees, brand placement, and quarterly partnership reviews.",
    [/membership|community|partner|referral|tier/i],
  ),
  multiParty(
    "36_three_party_integrator",
    "Three-Party Systems Integrator",
    "joint_venture",
    ["Apex Platform LLC", "Integra Partners Inc.", "ClientWorks Global Corp."],
    ["Apex", "Integra", "ClientWorks"],
    "Apex hosts software, Integra leads integration, ClientWorks funds rollout. Steering committee and dependency tracking across workstreams.",
    [/governance|integrat|dependency|steering|among/i],
    { minSignalHits: 1 },
  ),
];

export const PRO_OPERATIONAL_QA_ARCHETYPES = [
  ...new Set(PRO_OPERATIONAL_QA_FIXTURES.map((f) => f.archetype)),
];
