export {
  TEST504_ACCEPTED_PAID_BODY as TEST505_ACCEPTED_PAID_BODY,
  TEST504_HARBOR_PEAK as TEST505_HARBOR_PEAK,
  TEST504_INTAKE as TEST505_INTAKE,
  TEST504_PREPARED_FREEZE_CANDIDATE_HASH as TEST505_PREPARED_FREEZE_CANDIDATE_HASH,
  TEST504_RECIPIENT_CANDIDATES as TEST505_RECIPIENT_CANDIDATES,
  TEST504_RED_MESA as TEST505_RED_MESA,
  TEST504_STARTER_PREVIEW as TEST505_STARTER_PREVIEW,
  test504Draft as test505Draft,
} from "./paidProTest504Fixtures";

export const TEST505_AUTHORIZED_SIGNER_BULLET_1 =
  "* Sarah Mitchell, CEO, Red Mesa Logistics LLC";
export const TEST505_AUTHORIZED_SIGNER_BULLET_2 =
  "* Michael Torres, President, Harbor Peak Automation LLC";

export const TEST505_SIGNER_NAMES = ["Sarah Mitchell", "Michael Torres"] as const;
export const TEST505_SIGNER_TITLES = ["CEO", "President"] as const;
