import type { ParsedDraftShape } from "./intakeSmartDefaults";
import {
  TEST518_BLUE_HARBOR,
  TEST518_IRON_GATE,
  TEST518_PRODUCTION_QUAD_PARTY_INTAKE,
  TEST518_REDWOOD,
  TEST518_SUMMIT,
  test518Draft,
} from "./paidProTest518Fixtures";

export {
  TEST518_BLUE_HARBOR as TEST519_BLUE_HARBOR,
  TEST518_IRON_GATE as TEST519_IRON_GATE,
  TEST518_PRODUCTION_QUAD_PARTY_INTAKE as TEST519_PRODUCTION_QUAD_PARTY_INTAKE,
  TEST518_REDWOOD as TEST519_REDWOOD,
  TEST518_SUMMIT as TEST519_SUMMIT,
};

export const TEST519_PARTY_ROLES = [
  { name: TEST518_REDWOOD, role: "Client" },
  { name: TEST518_SUMMIT, role: "Lead Provider" },
  { name: TEST518_BLUE_HARBOR, role: "Implementation Partner" },
  { name: TEST518_IRON_GATE, role: "Cybersecurity Auditor" },
] as const;

export function test519Draft(): ParsedDraftShape {
  return test518Draft();
}

/** Production-class malformed ~2.5k server draft — wrong client, label-as-party, skeletal clauses. */
export function buildTest519MalformedProfessionalServerBody(): string {
  return [
    "CONSULTING SERVICES AGREEMENT",
    "",
    `This Agreement is entered into among ${TEST518_SUMMIT} ("Client"), ${TEST518_BLUE_HARBOR} ("Service Provider"), ${TEST518_IRON_GATE} ("Service Provider"), and Total Contract Value: ("Service Provider").`,
    "",
    "1. Scope of Services",
    `${TEST518_REDWOOD} is engaging the three providers listed above to deliver clinical data, AI model development, cloud hosting, and cybersecurity monitoring.`,
    "",
    "2. Payment Terms",
    "$420,000",
    "",
    "3. Services Term and Effective Date",
    "The term is twenty-four (24) months from the Effective Date.",
    "",
    "4. GOVERNING LAW",
    "This Agreement is governed by the laws of the State of Delaware.",
    "",
    "5. TERMINATION",
    "Termination terms to be agreed by the Parties.",
    "",
    "6. Notices",
    "Notice addresses will be provided during signer setup.",
    "",
    "Electronic signatures are permitted via LawDog.",
    "",
    `If to ${TEST518_SUMMIT}:`,
    "Notice address to be provided during signer setup.",
    "",
    `If to ${TEST518_BLUE_HARBOR}:`,
    "Notice address to be provided during signer setup.",
    "",
    `If to ${TEST518_IRON_GATE}:`,
    "Notice address to be provided during signer setup.",
    "",
    "If to Total Contract Value:",
    "Notice address to be provided during signer setup.",
    "",
    "IN WITNESS WHEREOF, the Parties execute this Agreement.",
    "",
    `${TEST518_SUMMIT}`,
    "By: _____________________________",
    "Name:",
    "Title:",
    "Date: _____________________________",
    "",
    `${TEST518_BLUE_HARBOR}`,
    "By: _____________________________",
    "Name:",
    "Title:",
    "Date: _____________________________",
    "",
    `${TEST518_IRON_GATE}`,
    "By: _____________________________",
    "Name:",
    "Title:",
    "Date: _____________________________",
    "",
    "Total Contract Value:",
    "By: _____________________________",
    "Name:",
    "Title:",
    "Date: _____________________________",
    "",
    "7. Miscellaneous",
    "The parties acknowledge this Agreement reflects the commercial understanding reached at intake.",
    "Each provider remains responsible only for its assigned scope of work and deliverables.",
    "Redwood Biologics retains approval rights over major project decisions jointly with Summit AI Consulting.",
    "Blue Harbor Systems shall maintain commercially reasonable uptime for hosted analytics pipelines.",
    "Iron Gate Security LLC shall provide continuous monitoring and documented incident response.",
    "Insurance, data privacy, dispute resolution, force majeure, assignment, amendment, severability, waiver, and entire agreement provisions are required but omitted from this draft placeholder.",
    "This placeholder paragraph exists only to reproduce a skeletal production-class server draft above the professional minimum length threshold without satisfying professional clause coverage.",
  ].join("\n");
}
